import type { Metadata } from "next";
import { MarketingNavigation } from "@/components/marketing/marketing-navigation";
import { MarketingFooter } from "@/components/marketing/marketing-footer";

export const metadata: Metadata = {
    title: "AI Architect Terms of Service — Trackr",
    description: "Terms governing participation in the Trackr AI Architect Program.",
    alternates: { canonical: "https://trytrackr.com/legal/architect-terms" },
    robots: { index: true },
};

export default function ArchitectTermsPage() {
    return (
        <>
            <main className="flex-grow w-full max-w-6xl mx-auto px-6">
                <MarketingNavigation isLoggedIn={false} />

                <section className="py-16 border-t border-black/10 max-w-3xl">
                    <span className="text-xs font-mono uppercase tracking-widest text-neutral-500 mb-4 block">Legal</span>
                    <h1 className="font-serif text-4xl font-normal mb-2">AI Architect Program Terms of Service</h1>
                    <p className="font-mono text-xs text-neutral-400 mb-12">Last updated: March 2026</p>

                    <div className="space-y-10 font-mono text-sm text-neutral-700 leading-relaxed">
                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">1. Program Overview</h2>
                            <p>The Trackr AI Architect Program (&ldquo;Program&rdquo;) enables qualified independent consultants, fractional executives, and agency partners (&ldquo;Architects&rdquo;) to refer prospective clients to Trackr and earn commissions on resulting subscriptions. Participation in the Program does not create an employment, partnership, or agency relationship. Architects are independent contractors and are solely responsible for their own taxes, insurance, and business obligations.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">2. Commission Structure</h2>
                            <p>Architects earn a commission of 20% of the net subscription revenue generated by each referred client. Commissions are calculated on successful invoice payments only. &ldquo;Net subscription revenue&rdquo; means the amount actually received by Trackr after refunds, chargebacks, and payment processing fees.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">3. Payment Terms</h2>
                            <p>Commissions are paid monthly via Stripe Connect. A minimum payout threshold of $50.00 USD applies. If your accrued balance is below the threshold, it rolls over to the next payment cycle. All payments are NET-30 following the close of the calendar month in which the underlying client invoice payment clears. Architects must complete Stripe Connect onboarding to receive payouts.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">4. Attribution</h2>
                            <p>Referral attribution is determined by the Architect&rsquo;s unique referral code (&ldquo;Arc Code&rdquo;). When a prospect visits Trackr via a URL containing the Architect&rsquo;s Arc Code and subsequently signs up for a paid subscription within 90 days, the Architect receives credit for that referral. First-touch attribution applies: if multiple Architects refer the same prospect, the first valid referral code used takes precedence.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">5. Exclusivity</h2>
                            <p>The Program is non-exclusive. Architects are free to promote, recommend, or partner with competing products and services. Trackr imposes no exclusivity requirements.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">6. Termination</h2>
                            <p>Either party may terminate participation in the Program with 30 days written notice (email is sufficient). Upon termination, Architects will continue to receive commissions on active referred clients for a period of 90 days following the termination date. After this wind-down period, all commission obligations cease. Trackr may terminate an Architect immediately and without notice for violations of Section 7 (Prohibited Conduct).</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">7. Prohibited Conduct</h2>
                            <p>Architects shall not: (a) send unsolicited bulk email (&ldquo;spam&rdquo;) or engage in deceptive marketing practices; (b) make false, misleading, or unsubstantiated claims about Trackr; (c) bid on Trackr brand keywords (including &ldquo;Trackr,&rdquo; &ldquo;trytrackr,&rdquo; or similar variations) in paid search advertising; (d) create fake accounts or fraudulent referrals; (e) impersonate Trackr employees or representatives; (f) violate any applicable law or regulation in promoting Trackr.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">8. Liability</h2>
                            <p>Trackr is not liable for client churn, non-payment, or subscription cancellation. Commissions are earned only on successful payments. In no event shall Trackr&rsquo;s total liability to any Architect exceed the commissions actually paid to that Architect in the twelve months preceding the claim.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">9. Modification</h2>
                            <p>Trackr may modify these terms at any time with 30 days email notice to the Architect&rsquo;s registered email address. Continued participation in the Program after the modification effective date constitutes acceptance of the updated terms.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">10. Governing Law</h2>
                            <p>These terms are governed by the laws of the State of Delaware, without regard to conflict of law principles. Any disputes shall be resolved in the state or federal courts located in Delaware.</p>
                        </div>
                    </div>
                </section>
            </main>
            <MarketingFooter />
        </>
    );
}
