"use client";

import { useState } from "react";
import { Link2, Mail, Check } from "lucide-react";

export function ShareActions({ toolName, token }: { toolName: string; token: string }) {
    const [copied, setCopied] = useState(false);
    const shareUrl = `https://trytrackr.com/share/${token}`;

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(shareUrl);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch {
            // Fallback for older browsers
            const input = document.createElement("input");
            input.value = shareUrl;
            document.body.appendChild(input);
            input.select();
            document.execCommand("copy");
            document.body.removeChild(input);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    const emailSubject = encodeURIComponent(`${toolName} — Research Report from Trackr`);
    const emailBody = encodeURIComponent(
        `Check out this AI-generated research report for ${toolName}:\n\n${shareUrl}\n\nGenerated by Trackr — research any tool in under 2 minutes.`
    );

    return (
        <div className="border border-black p-5">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div>
                    <h4 className="font-mono text-xs uppercase tracking-widest mb-1">Share this report</h4>
                    <p className="font-mono text-[10px] text-neutral-500">
                        Send this report to your team to inform their decision.
                    </p>
                </div>
                <div className="flex items-center gap-2">
                    <button
                        onClick={handleCopy}
                        className={`flex items-center gap-2 px-4 py-2 font-mono text-xs uppercase tracking-wide border transition-all ${
                            copied
                                ? "bg-black text-white border-black"
                                : "bg-white text-black border-black hover:bg-neutral-100 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[1px] hover:translate-y-[1px] hover:shadow-none"
                        }`}
                    >
                        {copied ? (
                            <>
                                <Check className="w-3 h-3" />
                                Copied
                            </>
                        ) : (
                            <>
                                <Link2 className="w-3 h-3" />
                                Copy Link
                            </>
                        )}
                    </button>
                    <a
                        href={`mailto:?subject=${emailSubject}&body=${emailBody}`}
                        className="flex items-center gap-2 px-4 py-2 font-mono text-xs uppercase tracking-wide border border-black bg-white hover:bg-neutral-100 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[1px] hover:translate-y-[1px] hover:shadow-none transition-all"
                    >
                        <Mail className="w-3 h-3" />
                        Email
                    </a>
                </div>
            </div>
        </div>
    );
}
