import type { Metadata } from "next";
import { MarketingNavigation } from "@/components/marketing/marketing-navigation";
import { MarketingFooter } from "@/components/marketing/marketing-footer";

export const metadata: Metadata = {
    title: "Affiliate Program Agreement — Trackr",
    description: "Commission structure, payment terms, and guidelines for the Trackr affiliate program.",
    alternates: { canonical: "https://trytrackr.com/legal/affiliate-agreement" },
    robots: { index: true },
};

export default function AffiliateAgreementPage() {
    return (
        <>
            <main className="flex-grow w-full max-w-6xl mx-auto px-6">
                <MarketingNavigation isLoggedIn={false} />

                <section className="py-16 border-t border-black/10 max-w-3xl">
                    <span className="text-xs font-mono uppercase tracking-widest text-neutral-500 mb-4 block">Legal</span>
                    <h1 className="font-serif text-4xl font-normal mb-2">Affiliate Program Agreement</h1>
                    <p className="font-mono text-xs text-neutral-400 mb-12">Last updated: March 2026</p>

                    <div className="space-y-10 font-mono text-sm text-neutral-700 leading-relaxed">
                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">1. Commission Rate</h2>
                            <p>Affiliates earn 20% of net subscription revenue generated by each referred client. &ldquo;Net subscription revenue&rdquo; means the amount received by Trackr after refunds, chargebacks, and payment processing fees. Commissions are calculated on each successful invoice payment.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">2. Payment Schedule</h2>
                            <p>Commissions are paid monthly via Stripe Connect. Payments are processed NET-30 after the close of the calendar month in which the underlying client payment clears. Minimum payout: $50.00 USD. Balances below the threshold carry forward to the next cycle.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">3. Attribution Window</h2>
                            <p>Referral attribution is tracked via the Affiliate&rsquo;s unique Arc Code. A prospect must sign up for a paid Trackr subscription within 90 days of clicking a link containing the Affiliate&rsquo;s Arc Code to qualify for commission credit. First-touch attribution applies.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">4. Chargebacks and Refunds</h2>
                            <p>If a referred client receives a refund within 60 days of their initial payment, the corresponding commission will be reversed. Commissions on disputed charges (chargebacks) are voided until the dispute is resolved in Trackr&rsquo;s favor.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">5. Tax Responsibility</h2>
                            <p>Affiliates are independent contractors and are solely responsible for all applicable taxes on commission income. For US-based Affiliates earning $600 or more in a calendar year, Trackr will issue a Form 1099-NEC. Affiliates may be required to provide a W-9 or equivalent tax form before receiving payouts.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">6. Intellectual Property</h2>
                            <p>Trackr grants Affiliates a limited, non-exclusive, revocable license to use Trackr&rsquo;s name, logo, and approved marketing materials solely for the purpose of promoting Trackr within the Program. All use must comply with Trackr&rsquo;s brand guidelines (available upon request). Affiliates may not modify Trackr&rsquo;s logo or create derivative marks.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">7. Termination</h2>
                            <p>Either party may terminate this agreement with 30 days written notice. Upon termination, the Affiliate will continue to receive commissions on active referred clients for 90 days. Trackr may terminate immediately for violations of program policies, including prohibited conduct as outlined in the Architect Terms of Service.</p>
                        </div>

                        <div>
                            <h2 className="font-serif text-xl font-normal mb-3 text-black">8. Governing Law</h2>
                            <p>This agreement is governed by the laws of the State of Delaware. Any disputes shall be resolved in the state or federal courts located in Delaware.</p>
                        </div>
                    </div>
                </section>
            </main>
            <MarketingFooter />
        </>
    );
}
