export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getBoardReportByToken } from "@/lib/actions/board-reports";
import { BoardReportView } from "@/components/reports/board-report-view";
import { TrackrLogo } from "@/components/common/trackr-logo";

export async function generateMetadata({
    params,
}: {
    params: Promise<{ token: string }>;
}): Promise<Metadata> {
    const { token } = await params;
    const report = await getBoardReportByToken(token);

    if (!report) return { title: "Report Not Found -- Trackr" };

    return {
        title: `${report.title} -- Trackr`,
        description:
            "Executive board report generated by Trackr -- AI tool intelligence platform.",
        openGraph: {
            title: report.title,
            description:
                "Executive board report generated by Trackr -- AI tool intelligence platform.",
            type: "article",
        },
    };
}

export default async function SharedBoardReportPage({
    params,
}: {
    params: Promise<{ token: string }>;
}) {
    const { token } = await params;

    const report = await getBoardReportByToken(token);
    if (!report) return notFound();

    return (
        <div className="min-h-screen bg-[#F3F3EF]">
            {/* Header */}
            <div className="border-b border-black bg-[#F3F3EF] px-6 py-4 flex items-center justify-between">
                <a
                    href="https://trytrackr.com"
                    className="flex items-center gap-2 font-serif text-xl font-medium hover:opacity-70"
                >
                    <TrackrLogo size={24} />
                    Trackr
                </a>
                <span className="font-mono text-[10px] uppercase tracking-widest text-neutral-400 border border-neutral-300 px-2 py-1">
                    Shared Report
                </span>
            </div>

            {/* Report Content */}
            <BoardReportView
                report={{
                    id: report.id,
                    title: report.title,
                    period: report.period,
                    createdAt: report.createdAt.toISOString(),
                    shareToken: report.shareToken,
                    data: report.data as Record<string, unknown>,
                }}
                isPublic={true}
            />

            {/* Footer CTA */}
            <div className="max-w-4xl mx-auto px-6 pb-8">
                <div className="border border-black bg-black text-white p-8 text-center">
                    <p className="font-mono text-xs text-neutral-400 mb-2 uppercase tracking-widest">
                        Powered by Trackr
                    </p>
                    <h3 className="font-serif text-xl font-normal mb-4 text-white">
                        AI tool intelligence for modern teams.
                    </h3>
                    <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
                        <a
                            href="https://trytrackr.com/sign-up"
                            className="inline-block bg-white text-black px-6 py-2.5 font-mono text-xs uppercase tracking-wide border border-white shadow-[4px_4px_0px_0px_rgba(255,255,255,0.25)] hover:translate-x-[1px] hover:translate-y-[1px] hover:shadow-[2px_2px_0px_0px_rgba(255,255,255,0.25)] transition-all"
                        >
                            Get Started Free
                        </a>
                        <a
                            href="https://trytrackr.com/pricing"
                            className="font-mono text-xs text-white/60 hover:text-white underline underline-offset-4"
                        >
                            View Pricing
                        </a>
                    </div>
                    <p className="font-mono text-[10px] text-white/30 mt-4">
                        No credit card required
                    </p>
                </div>
            </div>
        </div>
    );
}
